---
- name: Install Prometheus Node Exporter
  hosts: jenkins,sonarqube,nexus,postgresql,app_servers,monitoring
  become: yes
  vars:
    node_exporter_version: "1.7.0"
  tasks:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move binary to /usr/local/bin
      command: "mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/node_exporter"
      args:
        creates: /usr/local/bin/node_exporter

    - name: Create node_exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd, enable and start node_exporter
      systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started
