[bastion]
bastion ansible_host=<BASTION_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/securebank-key.pem

[jenkins]
jenkins ansible_host=<JENKINS_PRIVATE_IP> ansible_user=ubuntu

[sonarqube]
sonarqube ansible_host=<SONARQUBE_PRIVATE_IP> ansible_user=ubuntu

[nexus]
nexus ansible_host=<NEXUS_PRIVATE_IP> ansible_user=ubuntu

[monitoring]
monitoring ansible_host=<MONITORING_PRIVATE_IP> ansible_user=ubuntu

[postgresql]
postgresql ansible_host=<POSTGRES_PRIVATE_IP> ansible_user=ubuntu

[app_servers]
app_server_1 ansible_host=<APP1_PRIVATE_IP> ansible_user=ubuntu
app_server_2 ansible_host=<APP2_PRIVATE_IP> ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@<BASTION_PUBLIC_IP> -i ~/.ssh/securebank-key.pem"'
ansible_python_interpreter=/usr/bin/python3
