input {
  file {
    path => "/var/log/securebank/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "securebank-app"
  }
}

filter {
  if [type] == "securebank-app" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level}\s+%{DATA:logger} - %{GREEDYDATA:log_message}" }
    }
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "securebank-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
